config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => "users/registrations" }
  resources :pages do
    resource :comments, only: [:create, :update, :destroy]
  end
  root :to => 'pages#index'

end

app/views/pages/_comment_form.html.erb
<%= form_for(@comment, {url: page_comments_path(page_id: @page.id), role: 'form'}) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :comment %><br>
    <%= f.text_area :comment, rows: "5", class: "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
  <%= f.hidden_field :page_id %>
<% end %>

app/views/pages/_form.html.erb
<%= form_for(@page, {role: 'form'}) do |f| %>
  <% if @page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
      <% @page.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: "form-control"%>
  </div>
  <div class="field">
    <%= f.label :tag %><br>
    <%= f.text_field :tag, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body, rows: "20", class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :is_private %><br>
    <%= f.check_box :is_private %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pages/edit.html.erb
<%= render 'form' %>

<%= link_to 'Show', @page, {class: "btn btn-primary active",  role: "button"} %>
<%= link_to 'Back', pages_path, {class: "btn btn-default active",  role: "button"} %>
<br />
<br />

app/views/pages/index.html.erb
<div id="seach">
  <%= form_for @search_form, url: pages_path, method: :get, role: "form" do |f| %>
    <div class="pull-left col-xs-6">
      <%= f.text_field :body , placeholder: 'キーワードを入力してください', class: 'form-control' %>
    </div>
    <div class="pull-left">
      <%= link_to content_tag(:p, 'クリア', class: 'btn btn-default'), action: :index %>
    </div>
    <div class="pull-left">
      <%= f.submit '検索', class: 'btn btn-default' %>
    </div>
  <% end %>
</div>
<br />
<br />
<br />
<ul class="nav nav-tabs" role="tablist">
  <li class="<%= 'active' unless @search_form.is_private? %>"><%= link_to 'Feed', pages_path, role: "tab" %></li>
  <li class="<%= 'active' if @search_form.is_private? %>"><%= link_to 'Private', pages_path("page[is_private]" => true), role: "tab" %></li>
</ul>
<%= paginate(@pages) %>
<table id="search_result" class="table table-hover">
  <tbody>
    <% @pages.each do |page| %>
      <tr>
        <td class="page_title">
          <strong>
            <%= link_to page, class: 'jump_to' do %>
              <%= page.title %>&nbsp;&nbsp;<span class="badge alert-info"><%= page.comments.size unless page.comments.size == 0 %></span>
            <% end %>
          </strong>
        </td>
        <td><%= view_tags page.tag.split(',') if page.tag %></td>
        <td><div class="pull-right"><%= gravatar_for(page.user) %></div></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate(@pages) %>
<br>

app/views/pages/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', pages_path %>

app/views/pages/show.html.erb
<div id="main_area" class="row">
  <div id="show_area" class="col-md-9">
    <h1><%= @page.title %></h1>
    <br />
    <div>
      <span class="col-md-2">
        <div class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">目次 <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <% show_html, h_list = show_markdown(@page.body) %>
            <% if h_list.present? %>
              <% h_list.each_with_index do |v, k| %>
                <li>
                  <%= link_to "#header_no_#{k + 1}" do %>
                    <%= %[#{"&nbsp;" * (v[:level] - 1)}].html_safe %><%= v[:text] %>
                  <% end %>
                </li>
              <% end %>
            <% end %>
          </ul>
        </div>
      </span>
      <span class="col-md-10">
        <p>
          <%= view_tags @page.tag.split(',') %>
        </p>
      </span>
    </div>
    <div>
      <span class="">
        <p>
          <%= gravatar_for(@page.user) %> &nbsp;&nbsp;<%= @page.user.try(:name) || 'deleted_user' %>が<%= @page.created_at.to_time.strftime('%Y/%m/%d') %>に投稿しました。
          <% if @page.user_id == current_user.id || @page.user.blank? %>
            <%= link_to '削除', @page, method: :delete, data: { confirm: 'Are you sure?' } %> |
            <%= link_to '修正', edit_page_path(@page), {role: "button"} %>
          <% end %>
        </p>
      </span>
    </div>
    <div id="markdown">
      <hr>
      <p>
      <%= show_html %>
      </p>
    </div>
    <br />
    <br />
    <div id="comment_area">
      <% @comments.each do |v| %>
        <hr>
        <div class="clearfix">
          <div class=".pull-left">
            <%= markdown v.comment %>
          </div>
          <div class=".pull-left">
            <%= gravatar_for(v.user) %>&nbsp;&nbsp;<strong><%= v.user.try(:name)||'deleted_user' %></strong>&nbsp; <%= v.created_at.to_time.strftime('%Y/%m/%d %H:%M:%S') %>
            <%= link_to '削除', page_comments_path(page_id: @page.id, id: v.id), method: :delete, data: { confirm: 'Are you sure?' } if current_user.id == v.user_id %>&nbsp;&nbsp;
          </div>
        </div>
      <% end %>
      <br />
      <br />
      <hr>
      <%= render 'comment_form' %>
    </div>
    <br />
    <br />

    <%= link_to 'Back To List.', pages_path, {class: "btn btn-default active",  role: "button"} %>
    <br />
    <br />
  </div>
  <div id="side_area" class="col-md-3">
    <div class="panel panel-success">
      <div class="panel-heading">
        <%= gravatar_for(@page.user) %>&nbsp;&nbsp;<strong><%= @page.user.try(:name)||'deleted_user' %></strong>
      </div>
      <div class="panel-body">
        <ul>
          <% @page.user.last_pages.each do |v| %>
            <li><%= link_to v.title, page_path(v) %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>